// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MarkdownEditor
{
    internal sealed partial class Vsix
    {
        public const string Id = "9ca64947-e9ca-4543-bfb8-6cce9be19fd6";
        public const string Name = "Markdown Editor (32-bit)";
        public const string Description = @"A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.";
        public const string Language = "en-US";
        public const string Version = "1.13";
        public const string Author = "Mads Kristensen";
        public const string Tags = "markdown, editor, live preview";
    }
}
