// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MarkdownEditor
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "9ca64947-e9ca-4543-bfb8-6cce9be19fd6";
        public const string guidMarkdownEditorString = "b3984fb3-6a50-488a-a8a5-1ea6929adf43";
        public const string guidPackageCmdSetString = "82e1d55b-7e76-4319-ad60-94cc79c643c1";
        public static Guid guidPackage = new Guid(guidPackageString);
        public static Guid guidMarkdownEditor = new Guid(guidMarkdownEditorString);
        public static Guid guidPackageCmdSet = new Guid(guidPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ContextGroup = 0x0010;
        public const int SolutionExplorerGroup = 0x0020;
        public const int CopyAsHtml = 0x0100;
        public const int AddCustomStylesheet = 0x0200;
        public const int GenerateHtml = 0x0300;
        public const int EditorBold = 0x0400;
        public const int EditorInlineCode = 0x0420;
    }
}
