// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MarkdownEditor
{
				static class Vsix
				{
								public const string Id = "9ca64947-e9ca-4543-bfb8-6cce9be19fd6";
								public const string Name = "Markdown Editor";
								public const string Description = @"A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.";
								public const string Language = "en-US";
								public const string Version = "1.12";
								public const string Author = "Mads Kristensen";
								public const string Tags = "markdown, editor, live preview";
				}
}
